version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SITE_NAME=erp.luthfibarnik.com
      - DB_ROOT_PASSWORD=admin
      - ADMIN_PASSWORD=admin
      - INSTALL_APPS=erpnext,payments,hrms,lms
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - db
      - redis-cache
      - redis-queue

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - nginx-entrypoint.sh
    environment:
      - BACKEND=backend:8000
      - FRAPPE_SITE_NAME_HEADER=erp.luthfibarnik.com
      - SOCKETIO=websocket:9000
      - UPSTREAM_REAL_IP_ADDRESS=127.0.0.1
      - UPSTREAM_REAL_IP_HEADER=X-Forwarded-For
      - UPSTREAM_REAL_IP_RECURSIVE=off
      - PROXY_READ_TIMEOUT=120
      - CLIENT_MAX_BODY_SIZE=50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend

  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - redis-cache

  queue-default:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - bench
      - worker
      - --queue
      - default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - redis-queue
      - db

  redis-cache:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redis-queue-data:/data

  db:
    image: mariadb:10.6
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=admin
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  redis-cache-data:
  redis-queue-data:
  sites:
